import type { User } from "@/types/user"

export const mockUsers: User[] = [
    {
        id: "1",
        fullname: "John Doe",
        email: "john.doe@example.com",
        phone: "+1234567890",
        role: "admin",
        createAt: new Date(2024, 0, 1).toISOString(),
        updatedAt: new Date(2024, 1, 15).toISOString(),
        isDelete: false,
    },
    {
        id: "2",
        fullname: "Jane Smith",
        email: "jane.smith@example.com",
        phone: "+1234567891",
        role: "operator",
        createAt: new Date(2024, 0, 15).toISOString(),
        updatedAt: new Date(2024, 2, 1).toISOString(),
        isDelete: false,
    },
    {
        id: "3",
        fullname: "Bob Wilson",
        email: "bob.wilson@example.com",
        phone: "+1234567892",
        role: "tourist",
        createAt: new Date(2024, 1, 1).toISOString(),
        updatedAt: new Date(2024, 2, 10).toISOString(),
        isDelete: false,
    },
    {
        id: "4",
        fullname: "Alice Brown",
        email: "alice.brown@example.com",
        phone: "+1234567893",
        role: "operator",
        createAt: new Date(2024, 1, 15).toISOString(),
        updatedAt: new Date(2024, 2, 15).toISOString(),
        isDelete: false,
    },
    {
        id: "5",
        fullname: "Charlie Davis",
        email: "charlie.davis@example.com",
        phone: "+1234567894",
        role: "manager",
        createAt: new Date(2024, 2, 1).toISOString(),
        updatedAt: new Date(2024, 2, 20).toISOString(),
        isDelete: false,
    },
];
